apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: minimal-cluster
spec:
  teamId: "books"
  volume:
    size: 1Gi
  numberOfInstances: 1
  users:
    sammy:  # database owner
    - superuser
    - createdb
    foo_user: []  # role for application foo
  databases:
    flask_db: sammy  # dbname: owner
  preparedDatabases:
    bar: {}
  postgresql:
    version: "15"
#  patroni:
#    pg_hba:
#      - local     all  all  trust
#      - host      all  all  0.0.0.0/0   md5
